server:
  port: 9527
spring:
  application:
    name: gm-zuul-gateway
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最小空闲连接
        min-idle: 2
      timeout: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: gm-gatewall
  company.name: www.cloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  prefix: /dapeng  #服务前缀
  ignored-services: "*"  #原真实服务名忽略
  routes:
    user-cloud.serviceId: gmweb-feign
    user-cloud.path: /gm/**